// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUD.Models;

public partial class Customer
{
    public int CustomerId { get; set; }

    public string Firstname { get; set; }

    public string Lastname { get; set; }

    public string Adress { get; set; }

    public string Phone { get; set; }

    public virtual ICollection<Rent> Rents { get; } = new List<Rent>();
}